[general]
framerate = 60
bars = 0
bar_width = 3
bar_spacing = 1
sleep_timer = 3
[input]
method = pulse
source = auto
[output]
method = ncurses
channels = stereo
mono_option = average
[color]
background = '#090705'
gradient = 1
gradient_count = 6
gradient_color_1 = '#3b2412'
gradient_color_2 = '#65401c'
gradient_color_3 = '#8b5b25'
gradient_color_4 = '#b77b32'
gradient_color_5 = '#dca14c'
gradient_color_6 = '#f2cf7a'
[smoothing]
noise_reduction = 74
monstercat = 1
waves = 0
