[general]
framerate = 60
bars = 0
bar_width = 2
bar_spacing = 1
sleep_timer = 3
[input]
method = pulse
source = auto
[output]
method = ncurses
channels = stereo
mono_option = average
[color]
background = '#05080c'
gradient = 1
gradient_count = 6
gradient_color_1 = '#17334a'
gradient_color_2 = '#205579'
gradient_color_3 = '#28769d'
gradient_color_4 = '#3598ba'
gradient_color_5 = '#54bed0'
gradient_color_6 = '#9ae7e8'
[smoothing]
noise_reduction = 72
monstercat = 1
waves = 0
