[general]
framerate = 60
bars = 0
bar_width = 1
bar_spacing = 1
sleep_timer = 3
[input]
method = pulse
source = auto
[output]
method = ncurses
channels = stereo
mono_option = average
[color]
background = '#020604'
gradient = 1
gradient_count = 6
gradient_color_1 = '#063b20'
gradient_color_2 = '#075d2d'
gradient_color_3 = '#0a7f3b'
gradient_color_4 = '#12a64d'
gradient_color_5 = '#36cf69'
gradient_color_6 = '#98f5b2'
[smoothing]
noise_reduction = 70
monstercat = 1
waves = 0
