[general]
framerate = 60
bars = 0
bar_width = 1
bar_spacing = 0
sleep_timer = 3
[input]
method = pulse
source = auto
[output]
method = ncurses
channels = stereo
mono_option = average
[color]
background = '#08070b'
gradient = 1
gradient_count = 6
gradient_color_1 = '#30233d'
gradient_color_2 = '#49355d'
gradient_color_3 = '#64477c'
gradient_color_4 = '#80609a'
gradient_color_5 = '#9f7bb5'
gradient_color_6 = '#c4a1d4'
[smoothing]
noise_reduction = 68
monstercat = 0
waves = 1
