color_theme = "nocturne"
theme_background = False
truecolor = True
rounded_corners = False
graph_symbol = "braille"
shown_boxes = "cpu mem net proc"
update_ms = 1500
proc_sorting = "cpu lazy"
proc_colors = True
proc_gradient = True
proc_per_core = False
proc_mem_bytes = True
cpu_graph_upper = "total"
cpu_graph_lower = "gpu-totals"
show_uptime = True
check_temp = True
show_coretemp = True
show_disks = True
only_physical = True
net_auto = True
