# Nocturne / Obsidian Terminal
font_family      MesloLGS Nerd Font Mono
bold_font        auto
italic_font      auto
font_size        10.5
shell            /usr/bin/zsh --login

background       #07090a
foreground       #a7b8b1
selection_background #1b2925
selection_foreground #c3d0cb
cursor           #5f8f76
cursor_text_color #07090a
cursor_shape     beam
cursor_blink_interval 0.6
url_color        #6fa58c

color0  #07090a
color1  #9b5b5b
color2  #6d9578
color3  #9a895c
color4  #54756a
color5  #756b78
color6  #5f8f76
color7  #879a92
color8  #34413d
color9  #b36a6a
color10 #82ad8c
color11 #b29e6b
color12 #668e80
color13 #8c8090
color14 #6fa58c
color15 #c3d0cb

window_padding_width 8
background_opacity 0.98
dynamic_background_opacity yes
hide_window_decorations titlebar-only
remember_window_size yes
initial_window_width 120c
initial_window_height 34c
scrollback_lines 20000
confirm_os_window_close 0
enable_audio_bell no
tab_bar_style powerline
tab_bar_min_tabs 2
active_tab_background #365c4c
active_tab_foreground #c3d0cb
inactive_tab_background #0b0f10
inactive_tab_foreground #4d5d58
shell_integration enabled
